FROM golang:1.9

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libostree-dev \
        libglib2.0-dev \
        btrfs-tools \
    && apt-get clean

ENV GOPATH=/go
WORKDIR /go/src/github.com/bblfsh/bblfshd
